// frontend/src/utils/exportInvoicePdf.js
export async function generateInvoicePDF(invoice = {}, options = {}) {
  // dynamic import to avoid build-time bundling issues
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default || (m => m);

  const {
    company = {
      name: "BizMate",
      motto: "Your business companion",
      phone: "",
      email: ""
    },
    bank = {
      accountNumber: "0000000000",
      accountName: "BizMate",
      bankName: "Your Bank"
    },
    footerMessage = "Thank you for doing business with us.",
    watermarkText = "Generated by BizMate"
  } = options;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const left = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 40;

  // Header - Company name
  doc.setFontSize(18);
  doc.setTextColor("#4285F4"); // Google Blue
  doc.setFont("helvetica", "bold");
  doc.text(String(company.name || ""), left, y);

  // Motto
  doc.setFontSize(11);
  doc.setTextColor("#34A853");
  doc.setFont("helvetica", "normal");
  doc.text(String(company.motto || ""), left, y + 18);

  // Contact on right
  doc.setFontSize(10);
  doc.setTextColor("#000");
  if (company.phone) doc.text(`Phone: ${company.phone}`, pageWidth - left - 200, y);
  if (company.email) doc.text(`Email: ${company.email}`, pageWidth - left - 200, y + 12);

  // Invoice title and number
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#000");
  doc.text("INVOICE", pageWidth - left - 120, y + 50);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice ID: ${invoice.invoiceNumber || ""}`, pageWidth - left - 120, y + 70);

  y += 100;

  // Customer details
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", left, y);
  doc.setFont("helvetica", "normal");
  const cust = invoice.customer || {};
  doc.text(`${cust.name || "-"}`, left, y + 16);
  if (cust.email) doc.text(`${cust.email}`, left, y + 32);
  if (cust.phone) doc.text(`${cust.phone}`, left, y + 48);
  if (cust.address) doc.text(`${cust.address}`, left, y + 64);

  // Table - items
  const tableY = y + 90;
  const body = (invoice.items || []).map((it, idx) => ([
    String(idx + 1),
    it.name || "",
    it.quantity != null ? String(it.quantity) : "",
    it.price != null ? String(Number(it.price).toFixed(2)) : "",
    it.total != null ? String(Number(it.total).toFixed(2)) : ""
  ]));

  autoTable(doc, {
    startY: tableY,
    head: [["#", "Description", "Qty", "Rate", "Amount"]],
    body,
    styles: { fontSize: 10 },
    headStyles: { fillColor: [66, 133, 244], textColor: "#fff" },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 260 },
      2: { cellWidth: 40 },
      3: { cellWidth: 60 },
      4: { cellWidth: 80 }
    },
    margin: { left },
  });

  const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : tableY + 20;
  let totalsY = finalY + 20;

  // Totals box at right
  const rightX = pageWidth - left - 200;
  doc.setFontSize(11);
  doc.text(`Subtotal: ₦${(invoice.subtotal || 0).toFixed(2)}`, rightX, totalsY);
  doc.text(`Tax: ₦${(invoice.tax || 0).toFixed(2)}`, rightX, totalsY + 16);
  doc.text(`Discount: ₦${(invoice.discount || 0).toFixed(2)}`, rightX, totalsY + 32);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(`Grand Total: ₦${(invoice.totalAmount || 0).toFixed(2)}`, rightX, totalsY + 56);

  // Bank details & appreciation
  const bankY = totalsY + 100;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Bank Details:", left, bankY);
  doc.text(`Account: ${bank.accountNumber}`, left, bankY + 16);
  doc.text(`Account Name: ${bank.accountName}`, left, bankY + 32);
  doc.text(`Bank: ${bank.bankName}`, left, bankY + 48);

  doc.setFontSize(11);
  doc.text(footerMessage, left, bankY + 80);

  // Footer watermark
  doc.setFontSize(9);
  doc.setTextColor("#999999");
  doc.text(watermarkText, left, doc.internal.pageSize.getHeight() - 20);

  // Light tiled watermark pattern (small, faint text across page)
  const wmText = company.name || "BizMate";
  doc.setFontSize(8);
  doc.setTextColor(150,150,150);
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 0; i < 12; i++) {
    for (let j = 0; j < 8; j++) {
      const x = 30 + i * 120;
      const yy = 60 + j * 100;
      doc.textWithRotation(wmText, x, yy, { angle: -30, align: "left" });
    }
  }

  // Save file
  const filename = `${invoice.invoiceNumber || "invoice"}.pdf`;
  doc.save(filename);
}
