// import jsPDF from 'jspdf'
// import 'jspdf-autotable'

// const COLORS = {
//   blue: '#4285F4',
//   green: '#34A853',
//   red: '#EA4335',
//   yellow: '#FBBC05',
// }

// export function generatePDF({ items, businessName, motto, type='Quotation' }){
//   const doc = new jsPDF()

//   // Watermark
//   doc.setTextColor(200)
//   doc.setFontSize(50)
//   doc.text('Generated by BizMate', 35, 150, { angle: 35 })

//   // Header
//   doc.setTextColor(COLORS.blue)
//   doc.setFontSize(22)
//   doc.text(businessName || 'Business Name', 14, 20)

//   // Sub-header
//   doc.setTextColor(COLORS.green)
//   doc.setFontSize(14)
//   if (motto) doc.text(motto, 14, 28)

//   // Title
//   doc.setTextColor(0,0,0)
//   doc.setFontSize(16)
//   doc.text(type, 14, 40)

//   const tableBody = items.map((it, idx) => [
//     idx+1,
//     it.itemName || '',
//     it.quantity || 0,
//     it.unit || '',
//     it.price != null ? Number(it.price).toFixed(2) : '',
//     it.total != null ? Number(it.total).toFixed(2) : '',
//   ])

//   const grandTotal = items.reduce((sum, it) => sum + (Number(it.total)||0), 0)

//   doc.autoTable({
//     startY: 46,
//     head: [['#','Item','Quantity','Unit','Price','Total']],
//     body: tableBody,
//     styles: { halign: 'left' },
//     headStyles: { fillColor: [66,133,244], textColor: 255, fontStyle: 'bold' },
//     foot: grandTotal ? [['','','','','Grand Total', grandTotal.toFixed(2)]] : undefined,
//     footStyles: { fillColor: [52,168,83], textColor: 255, fontStyle: 'bold' },
//   })

//   doc.save(`${type.replace(' ','_')}.pdf`)
// }






// import { jsPDF } from "jspdf";
// import autoTable from "jspdf-autotable";

// export const generatePDF = ({ items = [], businessName = "", motto = "", type = "Quotation", grandTotal = 0 }) => {
//   const doc = new jsPDF();

//   // Header
//   doc.setFontSize(18);
//   doc.setTextColor("#4285F4");
//   doc.text(String(businessName || ""), 14, 20);

//   doc.setFontSize(12);
//   doc.setTextColor("#34A853");
//   doc.text(String(motto || ""), 14, 30);

//   // ✅ Ensure items is always an array
//   autoTable(doc, {
//     head: [["Item", "Quantity", "Unit", "Price", "Total"]],
//     body: (items || []).map(item => [
//       String(item.itemName || ""),
//       String(item.quantity || ""),
//       String(item.unit || ""),
//       item.price ? String(item.price) : "-",
//       item.total ? String(item.total) : "-"
//     ]),
//     startY: 40,
//   });

//   // Grand Total
//   doc.setFontSize(14);
//   doc.setTextColor("#000");
//   doc.text(`Grand Total: ${grandTotal}`, 14, (doc.lastAutoTable?.finalY || 50) + 10);

//   // Watermark
//   doc.setFontSize(10);
//   doc.setTextColor("#EA4335");
//   doc.text("Generated by BizMate", 14, 290);

//   doc.save("quotation.pdf");
// };


import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = ({
  items = [],
  businessName = "",
  motto = "",
  type = "Quotation",
  grandTotal = 0,
}) => {
  const doc = new jsPDF();

  // ==== HEADER (Business Name) ====
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#4285F4"); // Google Blue
  doc.text(businessName || "BizMate", 105, 20, { align: "center" });

  // ==== MOTTO (italic + green) ====
  if (motto) {
    doc.setFontSize(14);
    doc.setFont("times", "italic");
    doc.setTextColor("#34A853"); // Google Green
    doc.text(motto, 105, 28, { align: "center" });
  }

  // ==== DOCUMENT TYPE (Quotation / Stock List) ====
  doc.setFontSize(16);
  doc.setFont("helvetica", "bolditalic");
  doc.setTextColor("#EA4335"); // Google Red
  doc.text(type.toUpperCase(), 105, 38, { align: "center" });

  // Add a subtle underline under the type
  doc.setDrawColor("#EA4335");
  doc.setLineWidth(0.5);
  doc.line(70, 42, 140, 42);

  // ==== TABLE ====
  autoTable(doc, {
    startY: 50,
    head: [["Item", "Quantity", "Unit", "Price", "Total"]],
    body: (items || []).map((item) => [
      String(item.itemName || ""),
      String(item.quantity || ""),
      String(item.unit || ""),
      item.price ? `₦${item.price}` : "-",
      item.total ? `₦${item.total}` : "-",
    ]),
    theme: "grid",
    headStyles: {
      fillColor: "#4285F4", // Blue
      textColor: "#ffffff",
      fontSize: 12,
      fontStyle: "bold",
      halign: "center",
    },
    bodyStyles: {
      fontSize: 11,
      textColor: "#333333",
    },
    alternateRowStyles: {
      fillColor: "#f5f5f5", // Light gray stripes
    },
    styles: {
      cellPadding: 4,
      halign: "center",
    },
  });

  // ==== GRAND TOTAL BOX ====
  const finalY = doc.lastAutoTable.finalY || 70;
  doc.setFillColor("#FBBC05"); // Google Yellow background
  doc.setDrawColor("#EA4335"); // Red border
  doc.rect(14, finalY + 10, 180, 12, "FD"); // F=fill, D=draw border

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#000000");
  doc.text(`Grand Total: ₦${grandTotal}`, 105, finalY + 19, { align: "center" });

  // ==== FOOTER / WATERMARK ====
  doc.setFontSize(10);
  doc.setFont("times", "italic");
  doc.setTextColor("#999999");
  doc.text("Generated by BizMate", 105, 290, { align: "center" });

  // Save file
  doc.save(`${type}.pdf`);
};

